### ISSUE TITLE
exp/ticker: create a script to scrape asset data

### ISSUE THREAD

**Issue by accordeiro** [stellar/go#1080]
Create a function that scrapes `stellar.toml` data and stores the relevant assets in the db, so we'll later know which market data should be ingested.

The `anchor_asset` information should also be stored, since the current Ticker aggregates market info by asset type (e.g. all XLM/BTC markets are aggregated, regardless of issuer). If `anchor_asset` is undefined, we should fall back on `asset_code`.

**Tasks:**
- [x] Create script to fetch assets from Horizon, using the new API (#1095)
- [x] Implement logic to filter which assets are relevant / valid, similarly to StellarX's ticker (#1095)
- [x] Write tests for the filtering logic (#1095)
- [x] Validation of asset domains (comparing the organization and TOML urls), and also checking if the asset’s TOML url is actually valid and returns some info
- [x] Create A “FinalAsset” interface, which contains not only the info provided by the Horizon API, but also info that we’ve aggregated from other sources, like the TOML file
- [x] Create a function to process the Assets retrieved from Horizon, that will actually visit the TOML files and retrieve the missing data and build the FinalAsset info.
- [x] Improve the TOML verification performance, since it currently needs to request and verify ~10500 TOML files.
- [x] Database integration
- [x] ~Create a function for cleaning up old assets from the db (i.e. that are not listed on Horizon anymore)~ [we'll just used the `last_checked` and `last_valid` timestamps for filtering]
