### ISSUE TITLE
exp/ticker: create CLI to call Trade and Asset ingestion functions

### ISSUE THREAD

**Issue by accordeiro** [stellar/go#1133]
**Tasks:**

- [x] Create CLI project structure
- [x] Create command for refreshing assets
- [x] Create command for ingesting trades (backfill and stream)
- [x] Improve log messages across functions
- [x] Create command for migrating the database
