### ISSUE TITLE
Ingestion system and session

### ISSUE THREAD

**Issue by bartekn** [stellar/go#1310]
When the required components of the new ingestion system are ready:
- [x] `ledgerbackend` package and adapters https://github.com/stellar/go/issues/1285
- [x] `historyarchive` package, read/write interfaces https://github.com/stellar/go/issues/1134
- [x] `ingest/pipeline` package https://github.com/stellar/go/issues/961

we need to connect it all together using `ingest.System` and `ingest.Session` as described in https://github.com/stellar/go/blob/master/services/horizon/internal/docs/plans/new_horizon_ingest.md#tying-it-all-together.
