### ISSUE TITLE
Add `/offers` using new ingestion system.

### ISSUE THREAD

**Issue by abuiles** [stellar/go#1610]
Add a new route to horizon which allows consumer to load all available offers in Stellar. 

## TODO

- [x] Support pagination and ordering.

Support the following filters:

- [x] offers by seller
- [x] offers by selling_asset
- [x] offers by buying_asset

refs #1597

**Comment by bartekn** [comment]
Closed in #1627.

**Comment by bartekn** [comment]
[Close keywords](https://help.github.com/en/articles/closing-issues-using-keywords) work only with default branch only (`master` in our case). We cannot wait for release commits to be on `master` because it makes tracking milestone progress difficult (and in general would decrease open issues discoverability).

**Comment by abuiles** [comment]
@bartekn thanks for the explanation, I didn't know that!
