### ISSUE TITLE
Remove mysql support from Federation, and from repository as a dependency

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/go#1736]
#1706 made the decision that we should remove mysql support from Federation due to limited users of that functionality and a lack of maintenance and testing in comparison to the main database solutions the other reference service implementations use, PostgreSQL.

#1659 also cleaned up support for MySQL that was removed in Bridge and Compliance.

We should:
- [x] Remove MySQL from code and README for the Federation reference implementation. (stellar/go#1753)
- [x] Remove MySQL as a dependency of this repository, removing any dangling references, removing it from CircleCI config. (stellar/go#1753)
- [x] Remove MySQL from the guides and website docs in `stellar/doc` (stellar/docs#517)

**Comment by leighmcculloch** [comment]
Keeping open for stellar/docs#517.
