### ISSUE TITLE
[META] CAP23 support: Two-Part Payments with ClaimableBalanceEntry

### ISSUE THREAD

**Issue by abuiles** [stellar/go#2787]
## CAP23 support: Two-Part Payments with ClaimableBalanceEntry
This proposal introduces new operations that separate sending a payment from receiving the payment. [CAP 23](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0023.md) introduces a new ledger key type and a new set of operations.

This issue keeps track of related work to support CAP23 in the ingestion system, web API, and SDKs.

## Ingestion 
We need to extend the ingestion system to support CAP23. Depends on: 
- [x] https://github.com/stellar/go/issues/2858
- [x] https://github.com/stellar/go/issues/2882
- [x] https://github.com/stellar/go/issues/2887
- [x] https://github.com/stellar/go/issues/2886
- [x] https://github.com/stellar/go/issues/2885
- [x] #2882

## Web API

- [x] Web API  https://github.com/stellar/go/issues/2860

## SDKs

**TODO:** Create sub-issue for SDK related work, depends on Web API work #2860

- [ ] Support loading and filtering multiple claimable_balances.
- [ ] Support loading a single claimable_balance.
- [ ] Add support for claimable balance operations.

**Comment by tomerweller** [comment]
The suggested payload format of predicates is pretty cryptic right now. Horizon usually presents more readable resources.

There's some prior work around predicate trees in a JSON format. One notable example is mongodb's query [language](https://docs.mongodb.com/manual/reference/operator/query/and/).
 
I propose moving from a `{"type": i, "value": x}` format to a `{i_str: x}` format. 

## Example
### Original 
```json
"predicate": {
  "type": 1,
  "value": [
    {
      "type": 4,
      "value": "1594066025"
    },
    {
      "type": 3,
      "value": "1594066090"
    }
  ]
}
```

### Proposed
```json
"predicate": {
  "and" : [
    {"after": 1594066025},
    {"before": 1594066090}
  ]
}
```

**Comment by abuiles** [comment]
Horizon support for CAP23 has been completed.
