### ISSUE TITLE
[META] CAP33 support: Sponsored Reserve

### ISSUE THREAD

**Issue by abuiles** [stellar/go#2788]
https://github.com/stellar/stellar-protocol/blob/master/core/cap-0033.md

This proposal makes it possible to pay reserves for another account. This proposal extends ledger key type to make it possible to include the sponsor for it and also extends the list of operations to allow you to create, update, and remove sponsorships.

This following issue contain the work required to support CAP33 in the ingestion system, web API and SDKs.

## Ingestion

- [x] https://github.com/stellar/go/issues/2858
- [x] https://github.com/stellar/go/issues/2883
- [x] https://github.com/stellar/go/issues/2889
- [x] https://github.com/stellar/go/issues/2890  
- [x] https://github.com/stellar/go/issues/2891
- [x] https://github.com/stellar/go/issues/2888

## Web API

- [x] Web API https://github.com/stellar/go/issues/2862

### SDKs

**TODO:** Create sub-issue for SDK related work, depends on Web API work #2862

* Add a helper to create a sponsorship update operation. 
* Allow filtering resources by `sponsor`.

**Comment by abuiles** [comment]
Horizon support for CAP33 has been completed.
