### ISSUE TITLE
Release fast-txmeta architecture (Horizon 2.0)

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#3112]
### What problem does your feature solve?
We've implemented [fast txmeta](https://github.com/stellar/go/issues/2550), and it is available experimentally. Now we need to confirm suitability for production, and make it available to all.

### What would you like to see?

- [x] Use new `stellar-core run-from` command in Stellar-Core (#2842)
- [x] Kube files (#3123)
- [x] Fast txmeta Horizon is running on an internal SDF cluster
   - [x] Talk with ops team to resolve blockers
   - [x] Confirm crash/restart works reliably during online mode (#2611)
- [x] Last few [remaining issues](https://github.com/stellar/go/labels/fast-txmeta) are completed
- [x] Preferred production configuration is identified
   - [x] Different possible configurations are enumerated and tested for bugs (#3219)
   - [x] Create another ingesting instance in stg that is using `captive-core` wrapper. (#3212)
   - [x] Run a cluster with mirroring to ensure there are no performance bottlenecks under high load.
   - [ ] Test `POST /transactions` endpoint. (see: https://github.com/stellar/go/issues/3210#issuecomment-725018438)
- [x] Packaging and distribution approach is agreed
- [x] Packaging is implemented
- [x] Fast txmeta Horizon is deployed to testnet
  - [x] Create another prd cluster running captive-core. The existing database cluster serves as a backup.
- [x] Fast txmeta Horizon is deployed to pubnet
  - [x] Create another prd cluster running captive-core. The existing database cluster serves as a backup.
- [x] Docs, explainers and migration guide are complete
   - Docs, explainers https://github.com/stellar/go/issues/3205
   - Migration guide https://github.com/stellar/go/issues/3204
- [x] Fast txmeta released as Horizon 2.0
- [ ] Principle ecosystem Horizon users are supported with migration

**Comment by bartekn** [comment]
Looks like everything is done here. Close?

**Comment by ire-and-curses** [comment]
:tada: I think we still need to explicitly reach out to key ecosystem groups to get upgraded, but we can do that after the config file work in #3442 is done, as a separate task.
