### ISSUE TITLE
Add support for Asset Clawbacks (CAP 35)

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#3348]
https://github.com/stellar/stellar-protocol/blob/master/core/cap-0035.md

High priority tasks:
- [x] #3349 Update XDR definitions
- [x] #3350 Add support for `ClawbackOp`
- [x] #3351 Add support for account flag `AUTH_CLAWBACK_ENABLED_FLAG`
- [x] #3351 Add support for asset flag `CLAWBACK_ENABLED_FLAG`
- [x] Add support for the above in https://github.com/elucidsoft/dotnet-stellar-sdk ( @leighmcculloch ). WIP at https://github.com/stellar/dotnet-stellar-sdk/tree/cap35
- [x] #3368 Add integration test for the `Clawback` operation (needs a Core build with CAP35 support)
        - Replace the temporary stellar-core version and docker image by the definitive one once ready

Lower priority tasks:
- [x] #3378 Add support for the`SetTrustlineFlags` operation
       - It requires updating the XDR definitions with the changes at https://github.com/stellar/stellar-protocol/pull/838
- [x] https://github.com/stellar/go/issues/3448 Update XDR with the changes from https://github.com/stellar/stellar-protocol/pull/878#event-4409243096
- [x] #3356 Add support for `ClaimableBalanceEntryExtensionV1`
- [x] #3357 Add support for new error `SET_OPTIONS_AUTH_REVOCABLE_REQUIRED` in `txsub`
- [x] https://github.com/stellar/go/pull/3376 Add result codes for new operations in `txsub`
- [x] #3350 Add ingestion support for `ClawbackClaimableBalanceOp`
- [x] #3358 Add effects for `ClawbackOp` and `ClawbackClaimableBalanceOp`
- [x] Add `AccountCredited` effect for `ClawbackClaimableBalanceOp` ( leftover from https://github.com/stellar/go/pull/3358#discussion_r561784015 until we understand Core's behavior)
- [x]  #3379 Make sure there is support for all the above in the Go SDK
       - Add txnbuild support for all the new operations
       - Improve testing for the clawback operation https://github.com/stellar/go/pull/3364#discussion_r562759282
- [ ]  https://github.com/stellar/go/issues/3447 Make sure there are integration tests for all the operations (Already done some of it at #3422 #3424)
- [ ] Update documentation at https://github.com/stellar/new-docs (@Shaptic, #3449)
         - Add new operations
         - Add new effects
         - Add new operation details for pre-existing operations (if needed)
         - Add new Account flag (if needed)
         - Add new Trustline flag (if needed)
         - Add new Claimable Balance flag (if needed)
- [x] Add support in the Java SDK (@tamirms)
- [x] Add support in the JS SDK (@Shaptic)
- [x] Add support for all the above in the remaining SDKs (i.e. notify maintainers)

**Comment by Shaptic** [comment]
Going to close this since the only outstanding item is documentation and this is tracked in #3449.
