### ISSUE TITLE
Horizon: Protocol 19 Integration Tests

### ISSUE THREAD

**Issue by Shaptic** [stellar/go#4305]
Breakdown and Rollout: [Horizon & Protocol 19](https://docs.google.com/document/d/1qZ6o14JBOZpyDG6rNEd8Bj-sCzpeZgyx7Vtl1SMKI28). See #4261 for the master issue.

----------------------

Now that Protocol 19 feature work is mostly complete in the [horizon-protocol-19](https://github.com/stellar/go/tree/horizon-protocol-19) branch and the Go SDK is up-to-date, we can turn our focus to stability. We need end-to-end integration tests for the new features:

- [x] Generating full account extensions for state verifier tests (#4304)
- [x] Add stellar-core builds that include Protocol 19 work (#4312)
- [x] Test new CAP-21 account fields (#4322)
- [x] Test new transaction preconditions (#4320)
- [x] Test transaction submission queue (#4327)
- [x] Add state verifier tests for all of the above
- [x] Test Starlight (Leigh)

**Comment by jcx120** [comment]
Are there tests we should include for regressing re-ingestion and regular ingestion to keep up with ledger?

**Comment by Shaptic** [comment]
@jcx120 added an item re: state verifier. I think we get regression testing "automatically" by running our test suite without an actual Protocol 19 build of Stellar Core (aka what's been happening until #4306 gets merged), but moving forward yes, we need to ensure each new feature has the relevant ingestion testing (I think it did in their individual PRs).

**Comment by 2opremio** [comment]
> Add state verifier tests for all of the above

@Shaptic how do you suggest we do this? Changing TestStateVerifier to submit transactions with preconditions? Or are you just referring to the new Account fields?

**Comment by sreuland** [comment]
@2opremio , [PR #4332](https://github.com/stellar/go/pull/4332) is up for new integration test coverage on those remaining transaction preconditions.

**Comment by Shaptic** [comment]
@2opremio You're right that account extensions were supposed to have been tested! And preconditions aren't part of state, so we don't need to test those.

Unfortunately, the account extensions actually _weren't_ tested after #4304 because this line:
```go
{randxdr.FieldEquals("created.data.account.ext.v1.ext.v2.ext.v"), randxdr.SetU32(0)},
```
kept the extension disabled and I didn't realize that during the review :facepalm: 

This is resolved by #4337.
