### ISSUE TITLE
Contract Events API

### ISSUE THREAD

**Issue by jcx120** [stellar/go#4449]
RPC node is being built as part of core, so we should do this separately.

See relevant cap: https://github.com/stellar/stellar-protocol/blob/master/core/cap-0056.md

# TODO

- [ ] Figure out the two competing design differences
- [x] Figure out if it should be part of the horizon api or a separate tool
- [ ] Add some substories to do the work.
