### ISSUE TITLE
Horizon Lite -  Productionization / Optimization Epic

### ISSUE THREAD

**Issue by jcx120** [stellar/go#4571]
Epic for Productionalization and Optimization of Horizon Lite. Continuation from #4317 

## Backlog 
These are in order of importance:

- [ ] #4566
- [ ] #4503
- [ ] #4504
- [ ] #4506
- [ ] #4505

### R&D Tasks
This entails exploring use-cases for Horizon Lite besides the main MVP described above.

- [ ] #4473
- [ ] #4474
- [ ] #4497
- [x] #4459

<details>
  <summary>Archived Tasks</summary>

These are past work items that have been completed, kept around for visibility and historical tracking.

### Phase 1: Feature Work

- [x] https://github.com/stellar/go/issues/4212
- [x] Ingest via txmeta instead of from history archives
- [x] #4372
- [x] Investigate off-the-shelf data structures (e.g. [RoaringBitmap](https://github.com/RoaringBitmap/roaring). Conclusions: off-the-shelfs...
  * are slower for bitmaps, particularly the `NextActive()` equivalent
  * don't support all of the operations we need (e.g. insert vs. upserts, which may be important for non-txhash index use cases)
- Index (re)builder needs updating to build based on txmeta files, instead of history archives:
  * [x] single-process (`./index/cmd/single`)
  * [x] #4403
- [x] Complete `FileBackend.ReadAccounts()`
- [x] #4426
- [ ] Support real-time ingestion:
  * [x] Extend the `ledgerexporter` tool to allow unbounded ledger ranges
  * [x] #4406
  * [x] Integrate the above into request serving to ensure access to new ledger data as quickly as possible
  * [x] Add a version byte to the written txmeta files, in case we need to update the format in future.
- [x] #4430 
- [x] #4433 
- [x] The request parsing should mirror Horizon so that we can effectively do comparison testing in Phase 2. For example, right now we have `GET /operations?account=<id>` whereas in production we have `GET /account/<id>/operations`.
- [x] [starter on API docs with OAPI](https://github.com/stellar/go/pull/4431#discussion_r902026268)

### Phase 2: Correctness
Is the work we've done actually correct, i.e. Does it match what Horizon serves today?

There are two main questions here:
  1. Are we _generating_ indices correctly?
  2. Are we _using_ indices correctly?

- [x] Export pubnet ledger txmeta
- [x] Correctness: end-to-end tests for indexing jobs
- [x] #4475

### Phase 3: Going Live
In this phase, we'll actually be deploying the feature to real traffic and seeing how it performs.

#### Metrics
We want to easily be able to easily answer the question "How long does stuff take?" 
At minimum, we should include:

  - [x] #4451
  - [ ] [Minimum Dashboard for Testing / Verification](https://github.com/stellar/go/issues/4512)
   * Dashboards or some other form of at-a-glance analysis and comparison against existing infrastructure

#### Deployment
Work with Ops to build out infrastructure and deploy the branch. Questions we need to answer beforehand and tasks we need to complete:

  * [x] What kind of architecture should it have? 
  * [x] Do we want to mirror traffic from testnet or production?
  * [ ] Do we want to do ALB replays?
  * [ ] A build/deployment pipeline for easily updating the infra with changes
  * [ ] Approximate the $ cost of a production-ready architecture and compare it to the current one
  * [x] Dev/Demo deployment on infra - #4493 

#### MVP Testing
Understand viability of Lite design for real world conditions using our Steel thread impl. 
- [ ] [Understand request latency characteristics](https://github.com/stellar/go/issues/4514) (can it support web scale response)
  * [ ] Request profiling: history age vs variation of data
  * [ ] Hotspots (indices lookup > txmeta download > request processing etc)
- [ ] [Load testing](https://github.com/stellar/go/issues/4515) (is there a path to horizontal scaling)
- [ ] Confirm HW footprint (does it confirm our “solid state, constant” assumptions)
  * [ ] IO, RAM, CPU, Disk

#### Performance Optimization

  * [x] #4468
  * [x] Understand tradeoff between file-per-ledger and file-per-checkpoint
  * [x] Identify optimizations as needed to minimize high-latency operations (TBD based on the above, but e.g. minizing network round-trips)

### Phase 4: Everything Else
The remaining tasks are contingent on the success of Phase 3: if we deem that Horizon Lite is actually worth doing, there's quite a bit of work to getting everything else ready for production and public release.

- [ ] Indices
  * [x] Indices Updating Lifecycle POC
    * Note: currently indexes point to checkpoints. might need updating to point to ledgers? might be fine? tbd.
  * [ ] Complete buildout of indices (excluding Derived Data, eg: Trade Agg, Fee stats)
- [ ] Complete buildout of endpoints:
  * [ ] Accounts, transactions, operations
  * [ ] Other endpoints
  * [ ] Streaming: ensure streaming works for Ingestion Lite design pattern
- [x] Smart Contract Integration: https://github.com/stellar/go/issues/4358
- [ ] Public, distributed infrastructure for remote TX Meta and Indices
  * [x] Design minimal distributed infrastructure for generating, hosting files - #4483 
  * [x] Implement 1 SDF node for TX Meta and Indices
  * [ ] Develop plan to have other T1 operators generate/host
- [ ] Code refactors:
  * [ ] Should the leaf of a trie index be a bitmap? This is a clean way to combine the two index types.
  * [x] Optimize workers to work on entire checkpoint ranges rather than on individual ledgers (one flush per checkpoint)
  * [x] Unify filesystem abstractions, lots of variations around the codebase
  * [x] #4460
  * [ ] #4437
</details>
