### ISSUE TITLE
horizon: Add minimal support for Meridian's Soroban

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#4600]
Horizon already supports the upcoming Soroban XDR (#4576 ), however that's not enough. For Meridian, Horizon should be functional enough to:

1. Support the `soroban-rpc` server (provide support for `getAccounts` and txmeta info for the other rpc calls, e.g. for obtaining the events needed to implement`subscribeEvents`)
2. Support friendbot

At the very least, we need Horizon to be able to:

- [x] #4610 - Update ingestion and the transaction endpoint to provide `TransactionMetaV3` (which provides the contract events). Otherwise Horizon can't provide event information to soroban-rpc. 
- [x] https://github.com/stellar/go/issues/4604

It seems that Core will come with up a temporary data format, easier to deal with from Horizon's side. According to @MonsieurNicolas :
> for Meridian we're going to limit the changes needed in Horizon. Basically expose events via new meta format, but not require the tx result migration (that creates too many unknowns)
>
> you should have a version with the new endpoints enabled (as per the other thread). I am going to work with Graydon this afternoon to finalize on the meta format so you should get unblocked soon. We should be able to produce a custom build with that new format later this week (tomorrow maybe) as we already have a PR with most changes done

**Comment by tsachiherman** [comment]
The follow was removed from this issue after confirming with @sisuresh : 
- [ ] #4611 Deal with the fact that [`TransactionResult`s won't be present in the archives](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0056.md#stop-storing-transactionresults-in-archives) (this is what worries me the most, since I don't fully understand the implications of it
- [ ] #4611 - Ingest the new `LedgerCloseMetaV2` (which I assume is what the Soroban Captive Core will produce). Otherwise Ingestion won't work and won't be able to provide account info. The ledger backends need to be updated to support the new type.

**Comment by bartekn** [comment]
@tsachiherman this one was actually done in https://github.com/stellar/go/pull/4606:
> Ingest the new LedgerCloseMetaV2 (which I assume is what the Soroban Captive Core will produce). Otherwise Ingestion won't work and won't be able to provide account info. The ledger backends need to be updated to support the new type.

**Comment by tsachiherman** [comment]
> @tsachiherman this one was actually done in #4606:
> 
> > Ingest the new LedgerCloseMetaV2 (which I assume is what the Soroban Captive Core will produce). Otherwise Ingestion won't work and won't be able to provide account info. The ledger backends need to be updated to support the new type.

yes, this was confusing for me too.. which is why I just took it off and pasted it down here for archival purposes.
