### ISSUE TITLE
cli e2e testing (LocalNet)

### ISSUE THREAD

**Issue by tsachiherman** [stellar/go#4623]
## Conduct CLI end to end testing for the core soroban support

Sub tasks : 

- [x] update the Quickstart docker image with the latest core release. https://github.com/stellar/go/issues/4624
- [x] Run the existing integration tests against the updated quickstart docker to see if any breaking changes were introduced. https://github.com/stellar/go/issues/4625 
- [x] Use the CLI to deploy contract https://github.com/stellar/go/issues/4628
  - Use Soroban Examples, Hello world : sample from soroban-example, addi32 contract
- [x] Invoke a contract using JS https://github.com/stellar/go/issues/4629
- [x] Invoke a contract using Soroban CLI [@fons](https://stellarfoundation.slack.com/team/UV0P6ATT2)
  https://github.com/stellar/go/issues/4630
- [x] Use the CLI to create token https://github.com/stellar/go/issues/4627

for anyone doing e2e tasks, the latest docker image of quickstart to use for this is:

```
docker pull stellar/quickstart:pr-373-soroban-dev
docker run --platform linux/amd64 --rm -it -p "8000:8000" --name stellar stellar/quickstart:pr-373-soroban-dev --standalone --enable-soroban-rpc --protocol-version 20

```

soroban-rpc service URL entrypoint will be reachable from the locally run container at:
`http://localhost:8000/soroban/rpc`

[Quickstart soroban dev readme](https://github.com/stellar/quickstart/blob/4559_packaging_soroban/README.md#soroban-dev)

it has latest version of Horizon and Soroban-Rpc services from `soroban-xdr-next` branch
it has latest soroban core version - `19.4.1-1085.fc63f3a6a.focal~soroban`

**Comment by paulbellamy** [comment]
I'd say let's do the token thing last. A lot of stuff in core/xdr/env has changed recently, so that will likely be broken until the final builds/releases are made.

**Comment by sreuland** [comment]
paul, to confirm then, the abbreviated e2e flow we should be testing for now looks like:

1. checkout soroban-examples git repo, compile hello_world contract to wasm code 
2. chekcout soroban-cli, build it
3. deploy hello-world wasm contract using soroban-cli against the soroban-rpc service published from quickstart soroban-dev image (`http://localhost:8000/soroban/rpc`) which is running a standalone core #4628 
4. invoke the hello-world contract using browser(node/server-side?) javascript `sendTransaction` against quickstart soroban-rpc `http://localhost:8000/soroban/rpc` #4629
5. confirm the contract invocation via javascript `getTransactionStatus` against quickstart soroban-rpc `http://localhost:8000/soroban/rpc`  (#4629)


then when cli is ready, we can repeat but swap out #4/#5 to be #4630 to confirm both cli and js?
