### ISSUE TITLE
Soroban RPC API: Preflight Refactor (Epic)

### ISSUE THREAD

**Issue by jcx120** [stellar/go#4673]
Preflight was implemented using a temporary access to the core native RPC endpoint which will be deprecated (since it can easily contend with validator resources). 

- [ ] Spike: Embed Env Host into RPC Server (Rust in Go)
- [ ] Invoke smart contract using Env Host through Go 
- [ ] GetLedger(ID): Implement retrieval of ledger byID for applying pre-flight against, where ID is typically the last ledger closed. 
- [ ] Use Zenith Data backend for (last) ledger retrieval (fetch, ingest, serve).
