### ISSUE TITLE
Soroban RPC API: Events by Contract ID (EPIC)

### ISSUE THREAD

**Issue by jcx120** [stellar/go#4674]
Subscribe/Unsubscribe to push events via Websocket Subscription by ContractID MVP
  
- [ ] Event streaming / subscription API interface:
  - [ ] Finalize API design (for future extensibility by other topics)
  - [ ] Implement RPC endpoint: https://github.com/stellar/go/issues/4554
    - [ ] eventsSubscribe(ContractID) 
    - [ ] eventsUnsubscribe(ContractID) 
  - [ ] Implement CLI endpoint: https://github.com/stellar/soroban-cli/issues/61
- [ ] Data Backend
  - [ ] Spike: Design backend data pattern for supporting event pushes, ie:
    - simple current state XDR to JSON transformation
    - Implement Zenith Data Backend flow: TX Meta -> Index by Contract: AccountID, ingest, serve stream
  - [ ] Implement Data Backend to support event streaming

[References](https://stellarorg.atlassian.net/wiki/spaces/PJC/pages/4402151440/soroban-rpc+API+Docs#Websocket-Subscription)
