### ISSUE TITLE
[epic] export horizon database snapshots

### ISSUE THREAD

**Issue by mollykarcher** [stellar/go#4848]
We want to cut off the history of our SDF horizon instance to 1 year. To do this, we need to provide members of the ecosystem some mechanism for retrieving full history should they require it (and assuming they were previously relying on our public horizon instance). Note that this does _not_ encapsulate the work to actually drop the history beyond 1 year.

- [ ] Revive and review prior [spike](https://github.com/stellar/go/issues/4517) and it's [output](https://docs.google.com/document/d/1KhWYt9-v7UxqGtWOPWxjtM9SZkg0CKuhZGaTtnePfR8/edit#heading=h.5uel9fpp3rjq) to validate approach and assumptions. Break out additional tickets/issues and/or modify existing issues on this epic based on that
- [ ] (optional) Create/restore from AWS snapshots and validate behavior on startup
- [ ] Design export process using pg_dump (some additional context/thoughts in https://github.com/stellar/go/issues/4563)
- [ ] Design periodic update process for dumps/snapshots
- [ ] Design distribution mechanism and validate with security team (ex. BitTorrent)
- [ ] Update public-facing documentation to reflect the availability of snapshots and how to utilize them
- [ ] Create a public-facing document to articulate the plan for snapshots + history cutoff and start socializing this with the ecosystem
