### ISSUE TITLE
Improve Horizon Runbook

### ISSUE THREAD

**Issue by aditya1702** [stellar/go#4970]
Our current [Horizon Runbook](https://github.com/stellar/knowledge/blob/master/horizon/oncall.md) is in an internal repository and is hard to find. Moreover, it seems to be outdated and has not been updated in a while. This can be a problem for future incidents where we do not have a centralised place to look up some common solutions/fixes and reach out to partners. The following tasks can be tackled as part of this ticket: 

```[tasklist]
### Tasks
- [ ] Review and update the current runbook - one idea is to add links to all previous incidents and their post-mortem reports.
- [ ] Create an incident response/short release document so that partners and team members can reference it and coordinate a hotfix.
- [x] Add a section of current Horizon partners, their infrastructure setup and best way to reach out to them - #4962, #5048
```

**Comment by sydneynotthecity** [comment]
Internal runbook is hard to find: https://github.com/stellar/knowledge/blob/master/horizon/oncall.md 

Can we create an incident response, or shortened release document so that partners and newer team members can coordinate a hotfix when horizon needs patching?
