### ISSUE TITLE
Epic: Protocol 22 Changes

### ISSUE THREAD

**Issue by Shaptic** [stellar/go#5433]
# Protocol 22: Constructors

This epic defines all Horizon and SDK work that pertains to Protocol 22.

**References:**
 * [Core Timeline](https://docs.google.com/spreadsheets/d/1LFVpVbWfrNZExinwuX5BTslP04HBB2ng8OK_VkZb8PQ/edit)
 * CAP-58: [Soroban Constructors](https://stellar.org/protocol/cap-58)
 * High-performance HTTP server: stellar/stellar-core#4350
 * All Platform Protocol 22 issues: [projects#37/32](https://github.com/orgs/stellar/projects/37/views/32)

**Note**: All work should target a feature branch: RPC is [`v22-breaking-changes`](https://github.com/stellar/soroban-rpc/tree/v22-breaking-changes) and the Go monorepo is [`protocol-22`](https://github.com/stellar/go/tree/protocol-22).

-----------------------------------

## Phase 1: Support

This phase involves adding support for all of the plumbing we'll need for the actual feature work:
- [x] **Generate new protocol definitions**:
  * [x] Update Horizon to use new XDR: https://github.com/stellar/go/issues/5423
  * [x] Update RPC to use new XDR: Doable once the above is released.
  * [x] stellar/js-stellar-base#768
- [x] Update preflight to support both Protocol 21 & 22 hosts / XDR: https://github.com/stellar/soroban-rpc/pull/264
- [x] https://github.com/stellar/go/issues/5426

## Phase 2: Integration

This phase involves incorporating Core's changes across the stack as well as our own breaking changes:
- **Handle the new host function**: #5437
- **Refactoring RPC endpoints**:
  * [ ] https://github.com/stellar/soroban-rpc/issues/269
  * [x] https://github.com/stellar/soroban-rpc/issues/258
  * [x] #5455 
- **Remove deprecated Horizon fields**:
  * [x] https://github.com/stellar/go/issues/5438
